#!/usr/bin/env python3
"""Cross-model summary — the generalization evidence.

Emits one row per model showing that the byte-accounting taxonomy holds regardless of model family
and GQA configuration: the realized-byte fraction of the two simulation-only/incommensurable methods
(AdaKV, ThinK) at an aggressive nominal ratio, and whether the memory-faithful methods track the
diagonal. Also reports the GQA group and, if accuracy cells exist, whether a trivial method still
beats the query-aware scorer at matched bytes. Writes a LaTeX table (\\input-able) + prints it.

This is the figure-independent answer to "does it generalize beyond Qwen?".
"""
from __future__ import annotations

import sys
from collections import defaultdict

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from _figlib import load_cells, standard_args  # noqa: E402


def main() -> None:
    args = standard_args(__doc__)
    cells = [c for c in load_cells(args.results) if not c.get("failed")]
    audit = [c for c in cells if c.get("kind") != "accuracy" and "realized_fraction" in c]
    acc = [c for c in cells if c.get("kind") == "accuracy"]

    models = sorted({c["model"] for c in audit})
    if not models:
        sys.exit("[cross-model] no audit cells found.")

    rows = []
    for model in models:
        ma = [c for c in audit if c["model"] == model]
        # taxonomy check at the most aggressive shared ratio
        by_method = defaultdict(list)
        for c in ma:
            by_method[c["method"]].append((c["nominal_ratio"], c["realized_fraction"]))
        agg = max(r for c in ma for r, _ in [(c["nominal_ratio"], 0)])  # highest ratio present

        def frac_at(method, ratio):
            for r, f in by_method.get(method, []):
                if abs(r - ratio) < 1e-6:
                    return f
            return None

        adakv = frac_at("adakv", agg)
        think = frac_at("think", agg)
        # memory-faithful check: do random/streaming/snapkv track ~ (1-ratio)?
        mf_ok = True
        for meth in ["random", "streaming_llm", "snapkv"]:
            for r, f in by_method.get(meth, []):
                if abs(f - (1 - r)) > 0.05:
                    mf_ok = False
        n_kv = next((c.get("n_kv_heads") for c in ma if c.get("n_kv_heads")), None)

        # accuracy: at realized ~0.5, does streaming_llm beat snapkv? (RULER preferred)
        macc = [c for c in acc if c["model"] == model]
        if any(c.get("task") == "ruler" for c in macc):
            macc = [c for c in macc if c.get("task") == "ruler"]
        trivial_wins = "--"
        if macc:
            def acc_at(method, target=0.5):
                pts = sorted((c["realized_fraction"], c["accuracy"]) for c in macc
                             if c["method"] == method and c.get("realized_fraction"))
                best = None
                for f, a in pts:
                    if best is None or abs(f - target) < abs(best[0] - target):
                        best = (f, a)
                return best[1] if best else None
            s, k = acc_at("streaming_llm"), acc_at("snapkv")
            if s is not None and k is not None:
                trivial_wins = "yes" if s > k else "no"

        rows.append({
            "model": model.split("/")[-1], "n_kv": n_kv, "agg": agg,
            "adakv": adakv, "think": think, "mf_ok": mf_ok, "trivial_wins": trivial_wins,
        })

    # LaTeX
    lines = [
        "% Auto-generated by scripts/cross_model_summary.py — do not hand-edit.",
        "\\begin{tabular}{lccccc}",
        "\\toprule",
        "model & KV heads & AdaKV & ThinK & mem-faithful & trivial$>$query-aware \\\\",
        f" & & (bytes@r={rows[0]['agg']:.2f}) & (bytes) & on diagonal & @matched bytes \\\\",
        "\\midrule",
    ]
    for r in rows:
        a = f"{r['adakv']*100:.0f}\\%" if r["adakv"] is not None else "--"
        t = f"{r['think']*100:.0f}\\%" if r["think"] is not None else "--"
        lines.append(f"{r['model']} & {r['n_kv'] or '--'} & {a} & {t} & "
                     f"{'yes' if r['mf_ok'] else 'NO'} & {r['trivial_wins']} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"[cross-model] wrote {args.out}")
    print(f"{'model':28} {'KVh':>4} {'AdaKV':>7} {'ThinK':>7} {'mem-faith':>10} {'trivial>qa':>11}")
    for r in rows:
        a = f"{r['adakv']*100:.0f}%" if r["adakv"] is not None else "--"
        t = f"{r['think']*100:.0f}%" if r["think"] is not None else "--"
        print(f"{r['model']:28} {str(r['n_kv'] or '--'):>4} {a:>7} {t:>7} "
              f"{'yes' if r['mf_ok'] else 'NO':>10} {r['trivial_wins']:>11}")


if __name__ == "__main__":
    main()
