#!/usr/bin/env python3
r"""Table 1 — Kendall tau between the token-matched and byte-matched method rankings.

At each budget level we rank methods two ways and compare:
  - matched NOMINAL ratio: rank by accuracy at that nominal ratio.
  - matched REALIZED bytes: rank by accuracy interpolated at the equivalent byte fraction.
tau < 1 means correcting the resource unit reorders the methods — the quantitative form of the
claim. Emits a LaTeX booktabs table to --out (a .tex fragment \input by the paper).

Only memory-faithful methods can be byte-matched below full cache; simulation-only methods that
never reach the byte target are reported separately as INFEASIBLE, not ranked.
"""
from __future__ import annotations

import sys

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from _figlib import load_cells, standard_args  # noqa: E402


def kendall_tau(rank_a: list[str], rank_b: list[str]) -> float | None:
    """Kendall tau-a over the methods common to both orderings. None if <2 common items."""
    common = [m for m in rank_a if m in rank_b]
    if len(common) < 2:
        return None
    pos_b = {m: i for i, m in enumerate(rank_b)}
    order_a = [m for m in rank_a if m in common]
    conc = disc = 0
    for i in range(len(order_a)):
        for j in range(i + 1, len(order_a)):
            s = pos_b[order_a[i]] - pos_b[order_a[j]]
            if s < 0:
                conc += 1
            elif s > 0:
                disc += 1
    n = len(order_a)
    denom = n * (n - 1) / 2
    return (conc - disc) / denom if denom else None


def interp(pts: list[tuple[float, float]], x: float, eps: float = 1e-3) -> float | None:
    """Linear interpolation of accuracy at byte-fraction x. None only if x is meaningfully outside
    the measured range; a small eps absorbs float boundary noise (e.g. realized 0.8999 vs target 0.90)."""
    pts = sorted(pts)
    if not pts or x < pts[0][0] - eps or x > pts[-1][0] + eps:
        return None
    x = min(max(x, pts[0][0]), pts[-1][0])  # clamp into range after the tolerance check
    for (x0, y0), (x1, y1) in zip(pts, pts[1:]):
        if x0 <= x <= x1:
            if x1 == x0:
                return y0
            return y0 + (y1 - y0) * (x - x0) / (x1 - x0)
    return None


def main() -> None:
    args = standard_args(__doc__)
    cells = [c for c in load_cells(args.results) if c.get("kind") == "accuracy" and not c.get("failed")]
    if not cells:
        sys.exit("[table1] no accuracy cells — run kvbench.eval first.")
    if any(c.get("task") == "ruler" for c in cells):
        cells = [c for c in cells if c.get("task") == "ruler"]

    ctx = max(c["context_len"] for c in cells)
    cells = [c for c in cells if c["context_len"] == ctx]

    methods = sorted({c["method"] for c in cells})
    nominal_ratios = sorted({c["nominal_ratio"] for c in cells})

    # Per method: nominal->acc and byte_fraction->acc
    nom = {m: [] for m in methods}
    byt = {m: [] for m in methods}
    for c in cells:
        nom[c["method"]].append((c["nominal_ratio"], c["accuracy"]))
        if c.get("realized_fraction") is not None:
            byt[c["method"]].append((c["realized_fraction"], c["accuracy"]))

    rows = []
    for r in nominal_ratios:
        target_byte_fraction = 1.0 - r  # the byte level the field THINKS ratio r delivers
        # nominal ranking: methods by accuracy at nominal ratio r (desc)
        nom_acc = {m: dict(nom[m]).get(r) for m in methods}
        nom_rank = sorted([m for m in methods if nom_acc[m] is not None],
                          key=lambda m: -nom_acc[m])
        # byte ranking: methods by accuracy interpolated at target_byte_fraction (desc)
        byte_acc = {m: interp(byt[m], target_byte_fraction) for m in methods}
        byte_rank = sorted([m for m in methods if byte_acc[m] is not None],
                           key=lambda m: -byte_acc[m])
        infeasible = [m for m in methods if byte_acc[m] is None]
        tau = kendall_tau(nom_rank, byte_rank)
        rows.append((r, target_byte_fraction, tau, infeasible))

    # Emit LaTeX fragment.
    lines = [
        "% Auto-generated by scripts/table1_rank.py — do not hand-edit.",
        "\\begin{tabular}{cccl}",
        "\\toprule",
        "nominal ratio & implied byte frac. & Kendall $\\tau$ & byte-infeasible methods \\\\",
        "\\midrule",
    ]
    for r, bf, tau, infeas in rows:
        tstr = "n/a" if tau is None else f"{tau:.2f}"
        istr = ", ".join(infeas) if infeas else "---"
        lines.append(f"{r:.2f} & {bf:.2f} & {tstr} & {istr} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[table1] wrote {args.out}")
    for r, bf, tau, infeas in rows:
        print(f"  ratio {r:.2f}: tau={tau} infeasible={infeas}")


if __name__ == "__main__":
    main()
